// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"
)

type Category struct {
	ID        int64
	SpaceID   int64
	Type      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Goal struct {
	ID        int64
	SpaceID   int64
	Name      string
	Amount    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type PaymentMethod struct {
	ID        int64
	SpaceID   int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Space struct {
	ID        int64
	UserID    int64
	Nickname  string
	Balance   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type Subcategory struct {
	ID         int64
	SpaceID    int64
	CategoryID int64
	Name       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  *time.Time
}

type Transaction struct {
	ID            int64
	Name          string
	Type          string
	CategoryID    int64
	SubcategoryID *int64
	MethodID      int64
	Value         string
	SpaceID       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}

type User struct {
	ID        int64
	Email     string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}
