// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: spaces.sql

package repository

import (
	"context"
)

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces  (user_id, nickname, balance)
VALUES ($1, $2, 0)
RETURNING id, user_id, nickname, balance, created_at, updated_at, deleted_at
`

type CreateSpaceParams struct {
	UserID   int64
	Nickname string
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace, arg.UserID, arg.Nickname)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nickname,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSpacesByUserId = `-- name: ListSpacesByUserId :many
SELECT id, user_id, nickname, balance, created_at, updated_at, deleted_at FROM spaces 
WHERE user_id = $1
`

func (q *Queries) ListSpacesByUserId(ctx context.Context, userID int64) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpacesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nickname,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
